services:
  - type: web
    name: todo-spring-boot
    env: java
    plan: free
    buildCommand: ./mvnw -ntp -DskipTests package
    startCommand: java $JAVA_OPTS -jar target/todo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:/opt/render/project/src/data/todo-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
